Hash verify landinger bash wrapper

diff --git a/landinger b/landinger
--- a/landinger
+++ b/landinger
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 export LANDINGER_VERSION=v0.1
+export LANDINGER_SHA1=e7e016b9b171ab9b0bee02e6c61e39c8adeb893e
 export LANDINGER_FOLDER=~/.landinger
 export LANDINGER_JAR=$LANDINGER_FOLDER/landinger-$LANDINGER_VERSION.jar
 export LANDINGER_URL=https://github.com/soywiz/landinger/releases/download/$LANDINGER_VERSION/landinger.jar
@@ -9,13 +10,22 @@ mkdir -p "$LANDINGER_FOLDER"
 if ! test -f "$LANDINGER_JAR"; then
   if command -v wget > /dev/null 2>&1; then
     #echo "WGET"
-    wget -q -O "$LANDINGER_JAR" "$LANDINGER_URL"
+    wget -q -O "$LANDINGER_JAR.temp" "$LANDINGER_URL"
   elif command -v curl > /dev/null 2>&1; then
     #echo "CURL"
-    curl -s "$LANDINGER_URL" -o "$LANDINGER_JAR"
+    curl -s "$LANDINGER_URL" -o "$LANDINGER_JAR.temp"
   else
     echo "Can't find WGET or CURL"
   fi
+
+    SHA1=$(sha1sum "${LANDINGER_JAR}.temp" | cut -d' ' -f1)
+    if [ "$SHA1" == "$LANDINGER_SHA1" ]; then
+      cp -f "${LANDINGER_JAR}.temp" "$LANDINGER_JAR"
+      echo "DONE"
+    else
+      echo "Error downloading file: expected $LANDINGER_SHA1 but found $SHA1"
+      exit 1
+    fi
 fi
 
 java -jar "$LANDINGER_JAR" $*
